### PR TITLE
Kill the menu, scroll to last image.

### PR DESCRIPTION
**Pull request by rgbkrk**
This begins the hunt for heuristics to identify a good spot to take a screenshot.

The one introduced here:
- Removes the menu bar from nbviewer
- Grabs the last image on the page
- Scrolls down to the last image (or dies trying)

### CODE REVIEW

**Comment by rgbkrk** [comment]
Examples:

image

image

**Comment by rgbkrk** [comment]
It seems that it is ignoring my `el.scrollIntoView()`...

Any tips @jdfreder?

**Comment by rgbkrk** [comment]
Ah, to Phantom the whole page is in view and there is no scrolling. I can adjust where the screen grab happens but it is well before we can determine the position "client side" in Phantom.

**Comment by rgbkrk** [comment]
Gah, scrollTop didn't work either.

image

**Comment by rgbkrk** [comment]
I'm thinking, after viewing other people's tricks for this, that I should use phantom directly instead of webshot.

**Comment by rgbkrk** [comment]
http://nbviewer.ipython.org/gist/twiecki/3962843

becomes:

image

(but I'd rather have it focus on the plot).

**Comment by rgbkrk** [comment]
This is at least half decent. We'll start here and try out better heuristics after.

**Comment by jdfreder** [comment]
Sorry @rgbkrk I didn't see this ping for some reason, looks like you got it figured out though :cake:

**Comment by rgbkrk** [comment]
@jdfreder No problem. Yeah, I figured out what the issue was but not how to remedy it.

**Comment by jdfreder** [comment]
Casper seems to make this easy enough:
http://docs.casperjs.org/en/latest/modules/casper.html#index-29

You could write a script that waited for the page to load and notebook contents to render, measure the page height, and then snap a screen of the bottom of the notebook.

**Comment by rgbkrk** [comment]
That means I have to write a file and create a subprocess from node. Darn. Just not as slick as I wanted it to be.

**Pull request merged**
